// Generated by CoffeeScript 1.10.0
(function() {
  var OAuth, WooCommerceWpmlApi;

  OAuth = Npm.require('oauth-1.0a');

  WooCommerceWpmlApi = (function() {
    function WooCommerceWpmlApi(opt1) {
      this.opt = opt1;
      if (!this.opt.url) {
        throw new Error('url required');
      }
      if (!this.opt.consumerKey) {
        throw new Error('consumerKey required');
      }
      if (!this.opt.consumerSecret) {
        throw new Error('consumerSecret required');
      }
      this.classVersion = '1.0.4';
      this._setDefaultOptions(this.opt);
    }

    WooCommerceWpmlApi.prototype._setDefaultOptions = function(opt) {
      this.url = opt.url;
      this.lang = opt.lang || null;
      this.consumerKey = opt.consumerKey;
      this.consumerSecret = opt.consumerSecret;
      this.encoding = opt.encoding || 'utf8';
      this.version = opt.version || 'v3';
      return this.signature = opt.signature || 'HMAC-SHA256';
    };

    WooCommerceWpmlApi.prototype._getUrl = function(endpoint) {
      var url;
      url = '/' === this.url.slice(-1) ? this.url : this.url(+'/');
      url = url + 'wc-api/' + this.version + '/' + endpoint;
      if (!this.lang) {
        return url;
      } else {
        return url = url + '?lang=' + this.lang;
      }
    };

    WooCommerceWpmlApi.prototype._getOAuth = function() {
      var data;
      data = {
        consumer: {
          "public": this.consumerKey,
          secret: this.consumerSecret
        },
        signature_method: this.signature
      };
      return new OAuth(data);
    };

    WooCommerceWpmlApi.prototype._request = function(method, endpoint, data, callback) {
      var auth, url;
      url = this._getUrl(endpoint);
      auth = this._getOAuth.authorize({
        url: url,
        method: method
      });
      if (data) {
        parmas.body = JSON.stringify(data);
      }
      return HTTP.call(method, url, [
        {
          params: auth,
          data: data
        }
      ], callback);
    };

    WooCommerceWpmlApi.prototype.get = function(endpoint, callback) {
      return this._request('GET', endpoint, null, callback);
    };

    WooCommerceWpmlApi.prototype.post = function(endpoint, data, callback) {
      return this._request('POST', endpoint, data, callback);
    };

    WooCommerceWpmlApi.prototype.put = function(endpoint, data, callback) {
      return this._request('PUT', endpoint, data, callback);
    };

    WooCommerceWpmlApi.prototype["delete"] = function(endpoint, callback) {
      return this._request('DELETE', endpoint, null, callback);
    };

    return WooCommerceWpmlApi;

  })();

}).call(this);


//# sourceMappingURL=woocommerce-wpml.js.map
